---
title: "Gene set enrichment analysis: enrichR package"
author: "Axel Nohturfft"
date: "`r Sys.Date()`"
output: 
  html_notebook:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 3
    code_folding: "hide"
---

```{css}
h1 {background: darkblue;color: white;padding-left: 7px;}
h2 {color: darkblue;}
```


# Objective  
Perform programmatical gene set enrichment analsysi using enrichR package.  

```{r packages}
library(enrichR)
library(magrittr)
library(dplyr)
```


```{r}
setEnrichrSite("Enrichr") # Human genes
```

```{r}
websiteLive <- TRUE
```

```{r}
dbs <- listEnrichrDbs()
class(dbs) # "data.frame"
dim(dbs) # 171   5
```

```{r}
if (is.null(dbs)) websiteLive <- FALSE
if (websiteLive) head(dbs, 20)
```



```{r}
dbs1 <- c("ChEA_2013",
         "TRANSFAC_and_JASPAR_PWMs",
         "ENCODE_TF_ChIP-seq_2014",
         "Transcription_Factor_PPIs")
dbs2 <- c("GO_Molecular_Function_2015",
         "GO_Cellular_Component_2015",
         "GO_Biological_Process_2015")
```

## Load gene list from previous analysis
```{r}
list.files()
genez <- scan(file="STAT1_targets_1k.txt", what=character())
```


```{r}
if (websiteLive) {
    enriched <- enrichr(genez, dbs1)
}
class(enriched) # "list"
length(enriched) # 4
sapply(enriched, class) # >> all data frames
names(enriched)
```
Create one data frame with library name added:

```{r}
df.all <- lapply(seq_along(enriched), function(i) {
  df <- enriched[[i]]
  df$Library <- names(enriched)[i]
  df <- select(df, Library, everything())
}) %>% do.call(rbind, .) %>% 
  dplyr::filter(Adjusted.P.value <= 1e-05) %>% 
  dplyr::arrange(Adjusted.P.value)
dim(df.all) # 1283   10
head(df.all, 10)
```

```{r}
df.all %>% 
  dplyr::arrange(Adjusted.P.value) %>% 
  dplyr::select(Library, Term, Overlap, Adjusted.P.value) %>% 
  DT::datatable(.)
```


Finally, keep a record of the system settings and package versions:
```{r}
sessionInfo()
```

